# Site settings
title: "Paikchu's Tech Notes"
description: "A comprehensive collection of technology documentation, algorithm solutions, and development notes"
author: "Paikchu"
email: your-email@example.com # Update this with your actual email
baseurl: ""
url: "https://paikchu.github.io"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Database"
    url: "/database/"
  - title: "Algorithms"
    url: "/algorithms/"
  - title: "LeetCode"
    url: "/leetcode/"
  - title: "Network"
    url: "/network/"
  - title: "Environment Setup"
    url: "/environment/"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/